development: &DEV
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: workout_development
  pool: 5
  username: root
  password: root

test:
  <<: *DEV
  database: workout_test

production:
  <<: *DEV
  database: workout_production