development: &DEV
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: workout_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

test:
  <<: *DEV
  database: workout_test

production:
  <<: *DEV
  database: workout_production